# Generated by Django 3.0.6 on 2020-05-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currancies',
            new_name='Currencies',
        ),
    ]
