# Generated by Django 3.0.6 on 2020-05-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20200510_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
