# Generated by Django 3.0.6 on 2020-05-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_delete_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('currency_type', models.ForeignKey(default='Rupee', on_delete=django.db.models.deletion.CASCADE, to='currency.Currencies')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.UserProfile')),
            ],
            options={
                'db_table': 'user_wallet',
            },
        ),
    ]
