# Generated by Django 3.0.6 on 2020-05-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20200510_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='currency_code',
            field=models.CharField(default='INR', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='currency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currencies'),
        ),
    ]
