# Generated by Django 3.0.6 on 2020-05-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_foreigncurrencywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncurrencywallet',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currencies'),
        ),
    ]
