# Generated by Django 3.0.6 on 2020-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_auto_20200513_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigncurrencywallet',
            name='method',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='method',
        ),
        migrations.AlterField(
            model_name='transactionmethod',
            name='method',
            field=models.CharField(max_length=15),
        ),
    ]
