# Generated by Django 3.0.6 on 2020-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20200513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmethod',
            name='method',
            field=models.CharField(max_length=20),
        ),
    ]
