# Generated by Django 3.0.6 on 2020-05-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20200513_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionMethod',
        ),
    ]
