# Generated by Django 3.0.6 on 2020-05-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0017_transactionmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrencywallet',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.TransactionMethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwallet',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.TransactionMethod'),
            preserve_default=False,
        ),
    ]
