# Generated by Django 3.0.6 on 2020-05-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_auto_20200513_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.TransactionMethod'),
        ),
    ]
