# Generated by Django 3.0.6 on 2020-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_orderstatementmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatementmodel',
            name='method',
        ),
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='transaction_id',
            field=models.CharField(default='3DE7B444AFB740B892A4FC6BD5A10A4A', max_length=155),
        ),
        migrations.DeleteModel(
            name='TransactionMethod',
        ),
    ]
