# Generated by Django 3.0.6 on 2020-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20200513_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='transaction_id',
            field=models.CharField(default='521317FAC8A44F9782AD75DE882C570E', max_length=155),
        ),
    ]
