# Generated by Django 3.0.6 on 2020-05-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_auto_20200513_1515'),
        ('transfer', '0005_auto_20200513_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatementmodel',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.TransactionMethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='transaction_id',
            field=models.CharField(default='5FEA9F78728B43C6BD3C279506BD44CD', max_length=155),
        ),
    ]
