# Generated by Django 3.0.6 on 2020-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_auto_20200514_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='transaction_id',
            field=models.CharField(default='8FC8527F65DE4396B396FDE864B43D29', max_length=155),
        ),
    ]
