# Generated by Django 3.0.6 on 2020-05-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_auto_20200514_1746'),
        ('transfer', '0008_auto_20200514_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='from_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_wallet', to='currency.UserWallet'),
        ),
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.TransactionMethod'),
        ),
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='to_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_wallet', to='currency.UserWallet'),
        ),
        migrations.AlterField(
            model_name='orderstatementmodel',
            name='transaction_id',
            field=models.CharField(default='504D1CAEB1F74F10A90FD5ADD04C48C5', max_length=155),
        ),
    ]
